# Generated by Django 6.0.1 on 2026-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
