# Generated by Django 6.0.1 on 2026-03-17 14:20

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to=services.models.upload_image_path),
        ),
    ]
